FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-asyncio httpx

# Copiar el código de la aplicación
COPY . .

# Comando para ejecutar la aplicación y las pruebas
CMD ["sh", "-c", "pytest src/tests && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"] 